### ISSUE TITLE
T:Connect Patcher?

### ISSUE THREAD

**Issue by thorinEichenschild007** [DiaKEM/dexcom-g7-apk-patcher#2]
Hi,
you developed an amazing software, it helps me so much with my Dexcom device!
Thank you so so much for that!

Is it possible to develop a similar software for the T:Connect Mobile Application?
I would be very happy if you could do that!

Kind regards,
Thorin E.

**Comment by khskekec** [comment]
Hi Thorin,

great to hear that it was helpful for you. 

To be honest i don't have a clue what T:Connect is. I would check it out for you but cannot promise you when i will be able to do that.

Kind regards,
Selcuk

**Comment by khskekec** [comment]
Hey,

I am also from Germany, NRW. Unfortunately my son is diabetics and I did the patches for him. He is 5 and not able to carry Avery biggest phone which are usually on the market.

I did not have any touchpoints with T slim till now. Maybe you can just explain what the problem is. As I understood the Tslim is actually not able to communicate with the g7 right.

Your English is just fine 😊

Best regards

Selçuk

**Comment by khskekec** [comment]
Hey,

das müsste man entsprechend debuggen. Hast du denn die Apk aus den Staaten?

Ich würde dir sehr gerne dabei helfen und sehe dies nicht als "geopferte Zeit" an. Habe meine Zeit schon schwachsinniger verbracht 😉.

Viele Grüße

Selçuk

**Comment by khskekec** [comment]
Hi,

super. Schick mir die APK auch oder schick mir den Link zum Repo.

Dann schauen wir mal wie weit wir kommen.

Viele Grüße

Selçuk
