### ISSUE TITLE
 Apply version indicator patch error

### ISSUE THREAD

**Issue by wanya79** [DiaKEM/dexcom-g7-apk-patcher#20]
Hi there, it seems there is missing a file, how to fix that? 
 Apply version indicator patch error: dexcom-src/smali_classes4/ym/xLa.2.smali: No such file or directory

**Comment by khskekec** [comment]
Hi, 

Which operating system?

Best regards

Selçuk

**Comment by wanya79** [comment]
Ubuntu 22.04

Selcuk Kekec ***@***.***> schrieb am Do., 24. Nov. 2022,
20:23:

**Comment by mxsrm** [comment]
I have the same problem on up to date Arch Linux.

**Comment by khskekec** [comment]
Hi,

this known because apktool will generate different filenames on different operating systems. I am not sure whether this is only related to the version patch or also affects other patches. I will have to test it before. Might be that removing the version patch or providing a special one for linux/windows is enough to solve this problem for the moment.

**Comment by khskekec** [comment]
@wanya79 or @mxsrm Could you please validate whether it is working now?
If not please reopen this ticket!

**Comment by wanya79** [comment]
Yes, it is working.

Selcuk Kekec ***@***.***> schrieb am Fr., 25. Nov. 2022,
23:22:
